modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "mnamixin"
version = "${file.jarVersion}"

displayName = "MNA Mixin"
authors = "unilock"
description = '''
allows MNA to work with RER (in the worst way possible)
'''

[[dependencies.mnamixin]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mnamixin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mnamixin]]
modId = "mna"
mandatory = true
versionRange = "[1.7.2.10,)"
ordering = "NONE"
side = "BOTH"
